name: Rotation Serveur Minecraft

on:
  schedule:
    - cron: "0 7,15,23 * * *"
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium --with-deps

      - name: Run Worker
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          IP_NEW_SERVER: "orny"
          MODPACK_VERSION_ID: "1521"
          MODPACK_NAME: "Star Technology"
        run: python worker.py
